// 签证材料清单模板 - 10 种常见签证
//
// 每种签证的 items 是 JSON 数组：
// {category: "分组名", name: "材料名", nameEn: "英文名", required: true/false, note: "备注"}

export type ChecklistTemplateSeed = {
  visaType: string;
  visaName: string;
  items: Array<{
    category: string;
    name: string;
    nameEn?: string;
    required: boolean;
    note?: string;
  }>;
};

export const CHECKLIST_TEMPLATES: ChecklistTemplateSeed[] = [
  {
    visaType: "500",
    visaName: "500 学生签证",
    items: [
      { category: "入学", name: "入学确认书 CoE", nameEn: "Confirmation of Enrolment", required: true, note: "学校出具，含课程代码和费用" },
      { category: "入学", name: "Offer Letter", nameEn: "Offer Letter", required: true, note: "有条件/无条件录取通知" },
      { category: "入学", name: "学费缴纳凭证", nameEn: "Tuition Payment Receipt", required: true },
      { category: "身份", name: "护照", nameEn: "Passport", required: true, note: "有效期至少覆盖签证期 + 6 个月" },
      { category: "身份", name: "护照尺寸照片", nameEn: "Passport Photo", required: true, note: "白底，近 6 个月" },
      { category: "身份", name: "身份证复印件", nameEn: "National ID", required: false },
      { category: "身份", name: "出生公证", nameEn: "Birth Certificate", required: true, note: "公证处出具，带翻译" },
      { category: "陈述", name: "GS 真诚学生陈述", nameEn: "Genuine Student Statement", required: true, note: "1200-1800 字，参考知识库 GS 写作指南" },
      { category: "英语", name: "英语成绩单", nameEn: "English Test Report (IELTS/PTE/TOEFL)", required: true, note: "本科通常 IELTS 6.0+ 或 PTE 50+" },
      { category: "经济", name: "银行存款证明", nameEn: "Bank Statement", required: true, note: "至少覆盖第一年学费 + 生活费 AUD 29,710" },
      { category: "经济", name: "存款历史（6 个月流水）", nameEn: "6-Month Bank Transactions", required: true },
      { category: "经济", name: "资金来源说明", nameEn: "Financial Support Statement", required: true, note: "父母资助需提供关系证明 + 父母收入证明" },
      { category: "经济", name: "父母收入证明 / 税单", nameEn: "Parent Income Certificate", required: false, note: "父母资助时需要" },
      { category: "经济", name: "父母工作证明", nameEn: "Parent Employment Letter", required: false },
      { category: "保险", name: "OSHC 海外学生健康保险", nameEn: "Overseas Student Health Cover", required: true, note: "Bupa/Medibank/AHM 等，覆盖整个签证期" },
      { category: "健康", name: "体检报告", nameEn: "Health Examination", required: true, note: "指定医院 Panel Doctor 体检，HAP ID" },
      { category: "品行", name: "无犯罪记录证明", nameEn: "Police Clearance Certificate", required: true, note: "户籍所在地派出所开具" },
      { category: "学历", name: "最高学历证书公证", nameEn: "Degree Certificate (Notarized)", required: true },
      { category: "学历", name: "成绩单公证", nameEn: "Academic Transcript (Notarized)", required: true },
      { category: "学历", name: "在读证明（如适用）", nameEn: "Enrollment Certificate", required: false },
      { category: "其他", name: "过往签证拒签信（如有）", nameEn: "Previous Visa Refusal Letter", required: false, note: "有拒签史必须提供" },
      { category: "其他", name: "工作证明 / 简历（如有）", nameEn: "Employment Letter / CV", required: false, note: "有工作经验的成熟申请人" },
    ],
  },
  {
    visaType: "485",
    visaName: "485 毕业生工签",
    items: [
      { category: "身份", name: "护照", required: true },
      { category: "身份", name: "护照照片", required: true },
      { category: "学历", name: "完成信 Completion Letter", nameEn: "Course Completion Letter", required: true, note: "学校出具" },
      { category: "学历", name: "毕业证 / 学位证", nameEn: "Degree Certificate", required: true, note: "如尚未颁发，用完成信替代" },
      { category: "学历", name: "成绩单", nameEn: "Academic Transcript", required: true },
      { category: "英语", name: "英语成绩单", required: true, note: "IELTS 6.5 各项 5.5 或 PTE 58 各项 50。必须在申请前 1 年内考的" },
      { category: "保险", name: "OVHC 海外访客健康保险", nameEn: "Overseas Visitor Health Cover", required: true, note: "485 用 OVHC，不是 OSHC" },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录证明（AFP）", nameEn: "AFP National Police Check", required: true, note: "澳洲联邦警察局在线申请" },
      { category: "品行", name: "无犯罪记录证明（中国）", required: true, note: "如在中国居住 12 个月以上" },
      { category: "职业评估", name: "职业评估报告（Graduate Work Stream）", required: false, note: "Post-Vocational Stream 需要" },
      { category: "其他", name: "澳洲学习要求证明", nameEn: "Australian Study Requirement", required: true, note: "证明完成 2 年 CRICOS 注册课程" },
    ],
  },
  {
    visaType: "189",
    visaName: "189 独立技术移民",
    items: [
      { category: "身份", name: "护照", required: true },
      { category: "身份", name: "出生公证", required: true },
      { category: "身份", name: "护照照片", required: true },
      { category: "职业评估", name: "职业评估报告", nameEn: "Skills Assessment Report", required: true, note: "ACS/EA/VETASSESS 等，有效期 3 年" },
      { category: "英语", name: "英语成绩单", required: true, note: "Competent 最低门槛，Proficient/Superior 可加分" },
      { category: "EOI", name: "SkillSelect EOI 截图", required: true, note: "包含 EOI 号码和提交信息" },
      { category: "EOI", name: "邀请函 ITA", nameEn: "Invitation to Apply", required: true, note: "获邀后 60 天内递交" },
      { category: "工作", name: "工作证明信（每段工作）", nameEn: "Employment Reference Letter", required: true, note: "写明职位、职责、起止日期、每周小时数" },
      { category: "工作", name: "工资单 / 税单 / 社保", nameEn: "Payslips / Tax Records", required: true, note: "证明工作真实性" },
      { category: "学历", name: "学历证书公证", required: true },
      { category: "学历", name: "成绩单公证", required: true },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录（每个居住 12+ 月的国家）", required: true },
      { category: "配偶", name: "结婚证公证（如有配偶）", required: false },
      { category: "配偶", name: "配偶护照", required: false },
      { category: "配偶", name: "配偶英语成绩（如加分）", required: false },
      { category: "配偶", name: "配偶职业评估（如加分）", required: false },
      { category: "加分", name: "NAATI CCL 证书（如有）", required: false },
      { category: "加分", name: "Professional Year 完成证明（如有）", required: false },
      { category: "加分", name: "澳洲学习证明（如有）", required: false },
    ],
  },
  {
    visaType: "190",
    visaName: "190 州担保技术移民",
    items: [
      { category: "身份", name: "护照", required: true },
      { category: "身份", name: "出生公证", required: true },
      { category: "职业评估", name: "职业评估报告", required: true },
      { category: "英语", name: "英语成绩单", required: true },
      { category: "州担保", name: "州提名确认函", nameEn: "State Nomination Approval", required: true, note: "获州提名后 14 天内递交签证" },
      { category: "州担保", name: "州担保 ROI / 申请材料截图", required: true },
      { category: "EOI", name: "SkillSelect EOI 截图", required: true },
      { category: "EOI", name: "邀请函 ITA", required: true },
      { category: "工作", name: "工作证明信", required: true },
      { category: "工作", name: "工资单 / 税单", required: true },
      { category: "学历", name: "学历证书公证", required: true },
      { category: "学历", name: "成绩单公证", required: true },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录", required: true },
      { category: "配偶", name: "配偶材料（如适用）", required: false, note: "参考 189 配偶材料清单" },
      { category: "承诺", name: "居住承诺声明", required: true, note: "承诺在提名州居住 2 年" },
    ],
  },
  {
    visaType: "491",
    visaName: "491 偏远地区技术移民",
    items: [
      { category: "身份", name: "护照", required: true },
      { category: "身份", name: "出生公证", required: true },
      { category: "职业评估", name: "职业评估报告", required: true },
      { category: "英语", name: "英语成绩单", required: true },
      { category: "州担保", name: "州提名确认函", required: true },
      { category: "EOI", name: "SkillSelect EOI", required: true },
      { category: "EOI", name: "邀请函 ITA", required: true },
      { category: "工作", name: "工作证明信", required: true },
      { category: "工作", name: "工资单 / 税单", required: true },
      { category: "学历", name: "学历证书公证", required: true },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录", required: true },
      { category: "承诺", name: "偏远地区居住和工作承诺", required: true, note: "承诺在偏远地区居住工作 3 年" },
    ],
  },
  {
    visaType: "482",
    visaName: "482 Skills in Demand (SID)",
    items: [
      { category: "身份", name: "护照", required: true },
      { category: "雇主", name: "雇主提名确认", nameEn: "Nomination Approval", required: true },
      { category: "雇主", name: "雇佣合同", nameEn: "Employment Contract", required: true, note: "含薪资、职位、工作地点" },
      { category: "雇主", name: "公司 ABN / ACN 信息", required: true },
      { category: "职业评估", name: "职业评估（部分职业需要）", required: false },
      { category: "英语", name: "英语成绩单", required: true, note: "通常 IELTS 5.0 单项 5.0" },
      { category: "工作", name: "1 年相关工作经验证明", required: true, note: "过去 5 年内" },
      { category: "工作", name: "简历 / CV", required: true },
      { category: "学历", name: "学历证书", required: true },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录", required: true },
      { category: "保险", name: "健康保险", required: true },
    ],
  },
  {
    visaType: "186",
    visaName: "186 雇主担保永居 (ENS)",
    items: [
      { category: "身份", name: "护照", required: true },
      { category: "身份", name: "出生公证", required: true },
      { category: "雇主", name: "雇主提名确认", required: true },
      { category: "雇主", name: "雇佣合同", required: true },
      { category: "职业评估", name: "职业评估报告（DE Stream）", required: true, note: "Direct Entry 需要，TRT 不需要" },
      { category: "英语", name: "英语成绩单", required: true, note: "各项 IELTS 6.0" },
      { category: "工作", name: "3 年工作经验证明（DE）或 2 年为雇主工作证明（TRT）", required: true },
      { category: "学历", name: "学历证书公证", required: true },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录", required: true },
    ],
  },
  {
    visaType: "820",
    visaName: "820/801 境内伴侣签证",
    items: [
      { category: "身份", name: "申请人护照", required: true },
      { category: "身份", name: "担保人护照 / 公民证", required: true },
      { category: "身份", name: "出生公证（双方）", required: true },
      { category: "关系", name: "结婚证公证 / 关系注册证明", required: true, note: "事实婚姻需 12 个月同居证明" },
      { category: "关系", name: "双方关系陈述（分别手写）", nameEn: "Statement of Relationship", required: true, note: "8-15 页，从相识到现在" },
      { category: "关系", name: "Form 888 法律声明（2-3 份）", required: true, note: "由澳洲公民/PR 亲友签字" },
      { category: "关系-经济", name: "联名银行账户 / 共同账单", required: true, note: "证明经济共同" },
      { category: "关系-经济", name: "共同租约 / 房贷合同", required: true },
      { category: "关系-家庭", name: "同居地址证明", required: true, note: "双方不同邮件寄到同一地址" },
      { category: "关系-家庭", name: "家庭合照（不同时期）", required: true },
      { category: "关系-社交", name: "社交活动照片", required: true, note: "与双方家人/朋友的合照" },
      { category: "关系-社交", name: "聊天记录截图（精选 + 翻译）", required: true },
      { category: "关系-社交", name: "共同旅行记录", required: false, note: "机票、酒店、签证盖章" },
      { category: "关系-承诺", name: "长期规划证据", required: false, note: "共同购物、宠物、保险受益人" },
      { category: "担保人", name: "担保人身份证明", required: true },
      { category: "担保人", name: "担保人收入证明 / 税单", required: false },
      { category: "担保人", name: "Form 40SP 担保表格", required: true },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录", required: true },
      { category: "费用", name: "VAC 缴费凭证", required: true, note: "AUD 9,365（2025 年 7 月后）" },
    ],
  },
  {
    visaType: "143",
    visaName: "143 付费父母移民",
    items: [
      { category: "身份", name: "父母护照", required: true },
      { category: "身份", name: "出生公证（父母 + 子女）", required: true },
      { category: "家庭", name: "亲子关系公证", required: true },
      { category: "家庭", name: "Balance of Family Test 证据", required: true, note: "证明一半以上子女在澳" },
      { category: "担保", name: "子女的担保声明", required: true },
      { category: "担保", name: "子女的收入证明", required: true },
      { category: "担保", name: "Assurance of Support (AoS) 经济担保金", required: true, note: "AUD 10,000+ 押金" },
      { category: "健康", name: "体检", required: true },
      { category: "品行", name: "无犯罪记录", required: true },
      { category: "费用", name: "VAC1 缴费凭证", required: true },
      { category: "费用", name: "VAC2（获批前缴纳）", required: true, note: "约 AUD 43,600" },
    ],
  },
  {
    visaType: "600",
    visaName: "600 访客签证",
    items: [
      { category: "身份", name: "护照", required: true, note: "有效期至少 6 个月" },
      { category: "身份", name: "护照照片", required: true },
      { category: "目的", name: "旅行计划 / 行程表", required: true },
      { category: "目的", name: "邀请函（探亲类）", required: false, note: "澳洲亲友出具" },
      { category: "目的", name: "酒店预订确认（旅游类）", required: false },
      { category: "经济", name: "银行存款证明", required: true },
      { category: "经济", name: "近 6 个月银行流水", required: true },
      { category: "经济", name: "在职证明 / 营业执照", required: true, note: "证明祖国约束力" },
      { category: "经济", name: "房产证 / 车辆登记", required: false, note: "增强祖国约束力" },
      { category: "家庭", name: "户口本公证", required: false },
      { category: "健康", name: "体检（75 岁以上必须）", required: false },
      { category: "保险", name: "旅行保险", required: false, note: "建议购买" },
    ],
  },
];
